# System Packages (nixpkgs)
# -----------------------------------------------------------------------------
[pkg] # WE ARE DECLARATIVE NOW!!!!!!

setup = { cmd = "bash ~/.config/ch/scripts/nixos/setup.sh", confirm = "yesorno", msg = "This will modify your configuration.nix to import packages.nix. Proceed?" }

install = "bash ~/.config/ch/scripts/nixos/install.sh {1}"

remove = "bash ~/.config/ch/scripts/nixos/remove.sh {1}"
