# System Packages (xbps)
# -----------------------------------------------------------------------------
[app]
update = "sudo xbps-install -Su"
install = "sudo xbps-install {1}"
remove = "sudo xbps-remove {1}"
search = "xbps-query -Rs {1}"
info = "xbps-query -R {1}"
list_installed = "xbps-query -l"

# Cleanup / Cache Management
# -----------------------------------------------------------------------------
[clean]
clear_cache = "sudo xbps-remove -O"
remove_orphans = "sudo xbps-remove -o"
cache_size = "du -sh /var/cache/xbps"
