# Rice (to be added)
# -----------------------------------------------------------------------------
[rice]
# Soon

# Dotfiles (to be added)
# -----------------------------------------------------------------------------
[dots]
# Soon
