active_distro = "void"

# System Packages (xbps)
# -----------------------------------------------------------------------------
[app]
update = "sudo xbps-install -Su"
install = "sudo xbps-install {1}"
remove = "sudo xbps-remove {1}"
search = "xbps-query -Rs {1}"
info = "xbps-query -R {1}"
list_installed = "xbps-query -l"

# System Utilities
# -----------------------------------------------------------------------------
[sys]
list_usb = "lsusb"
list_partitions = "lsblk -f"
disk_space = "df -h"
processes = "btop"
make_executable = "chmod +x {1}"
create_folder = "mkdir -p {1}"

# Boot Utilities
# -----------------------------------------------------------------------------
[boot]
flash_iso = "sudo dd if={1} of={2} bs=4M status=progress oflag=sync"
format_fat32 = "sudo mkfs.vfat -F 32 {1}"
format_ext4 = "sudo mkfs.ext4 {1}"
unmount = "sudo umount {1}"
update_grub = "sudo grub-mkconfig -o /boot/grub/grub.cfg"

# File Editing
# -----------------------------------------------------------------------------
[edit]
read = "cat {1}"
write = "micro {1}"

# Rice (to be added)
# -----------------------------------------------------------------------------
[rice]
# Soon

# Dotfiles (to be added)
# -----------------------------------------------------------------------------
[dots]
# Soon

# Services and Daemons
# -----------------------------------------------------------------------------
[service]
start = "sudo sv up {1}"
stop = "sudo sv down {1}"
restart = "sudo sv restart {1}"
status = "sudo sv status {1}"
enable = "sudo ln -s /etc/sv/{1} /var/service/"
disable = "sudo rm -f /var/service/{1}"
list_all = "ls -l /var/service/"
list_available = "ls /etc/sv/"

# Cleanup / Cache Management
# -----------------------------------------------------------------------------
[clean]
clear_cache = "sudo xbps-remove -O"
remove_orphans = "sudo xbps-remove -o"
cache_size = "du -sh /var/cache/xbps"

# Networking
# -----------------------------------------------------------------------------
[net]
show_ip = "ip a"
ping = "ping -c 4 {1}"
list_wifi = "nmcli device wifi list"
connect_wifi = "nmcli device wifi connect {1} password {2}"
status = "nmcli general status"
restart = "sudo sv restart NetworkManager"

# User Management
# -----------------------------------------------------------------------------
[user]
add = "sudo useradd -m {1}"
set_password = "sudo passwd {1}"
list_all = "cut -d: -f1 /etc/passwd"
list_groups = "groups {1}"

# Logs Diagnostics
# -----------------------------------------------------------------------------
[log]
kernel = "dmesg"
service = "cat /var/log/{1}/current"

# Hardware info
# -----------------------------------------------------------------------------
[hardware]
cpu_info = "lscpu"
memory_info = "free -h"
temperatures = "sensors"
gpu_info = "lspci -k | grep -A 3 -i vga"
devices = "lspci"